<?php

/**
* @file
* Provides IIT Global Header
*/

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function iit_global_header_help($path, $arg) {
  switch ($path) {
    case 'admin/help#iit_global_header':
      return '<p>' . t('Provides an IIT Global Header block for use in IIT sites. This block pulls info from a menu service located in the main IIT install. The URL of the menu service and other options can be set in the configuration page.') . '</p>';
      break;
  }
}

/**
 * Implements hook_block_info().
 */
function iit_global_header_block_info() {
  $blocks['iit_global_header'] = array(
    'info' => t('IIT Global Header'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function iit_global_header_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'iit_global_header':
      $block['subject'] = t('IIT Global Header');
      $block['content'] = t('<h1>Header not implemented yet!</h1>');
      break;
  }

  return $block;
}