<?php

/**
* @file
* Provides IIT Global Header
*/

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function iit_global_header_help($path, $arg) {
  switch ($path) {
    case 'admin/help#iit_global_header':
      return '<p>' . t('Pulls the IIT Global Header from the web.iit.edu domain and creates a block for display in the global header region.') . '</p>';
      break;
  }
}