<?php

/**
* @file
* Provides IIT Global Header block from JSON menu service
*/

define('IIT_GH_PRIMARY_MENU_SERVICE_URL', 'http://web-dev.iit.edu/api/test/menu/menu-iit-global-menu.json');
define('IIT_GH_SECONDARY_MENU_SERVICE_URL', 'http://web-dev.iit.edu/api/test/menu/menu-iit-global-secondary-menu.json');


/* ***************************************** */
/* Hook Implementations                      */
/* ***************************************** */

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function iit_global_header_help($path, $arg) {
  switch ($path) {
    case 'admin/help#iit_global_header':
      return '<p>' . t('Provides an IIT Global Header block for use in IIT sites. This block pulls info from a JSON Rest service located in the main IIT install. The URL of the menu service and other options can be set in the configuration page. This module requires the Drupal install providing the menu service to use the Drupal Services module and Menu Services module to provide the web service.') . '</p>';
      break;
  }
}

/**
 * Implements hook_permission().
 */
function iit_global_header_permission() {
  return array(
    'administer iit_global_header' => array(
      'title' => t('Administer IIT Global Header module'),
      'description' => t('Perform administration tasks and configure IIT Global Header module'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function iit_global_header_menu() {
  $items = array();

  $items['admin/config/content/iit_global_header'] = array(
    'title' => 'IIT Global Header',
    'description' => 'Configuration for the IIT Global Header module.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('iit_global_header_config_form'),
    'access arguments' => array('administer iit_global_header'),
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function iit_global_header_block_info() {
  $blocks['iit_global_header'] = array(
    'info' => t('IIT Global Header'),
    'cache' => DRUPAL_CACHE_CUSTOM,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function iit_global_header_block_view($delta = '') {
  // Get block contents from cache if possible.
  $cache = cache_get($delta, 'cache_block');
  if (!empty($cache) && isset($cache->data) && !empty($cache->data)) {
    return $cache->data;
  }

  // No cache, generate the block output.
  $block = array();

  switch ($delta) {
    case 'iit_global_header':
      if (user_access('access content')) {
        //$block['subject'] = t('IIT Global Header');
        $block['content'] = iit_global_header_build_contents();
      }
      break;
  }

  // Set block contents in cache for 5 mins.
  cache_set($delta, $block, 'cache_block', REQUEST_TIME + 300);

  return $block;
}


/* ***************************************** */
/* Form Builders                             */
/* ***************************************** */

/**
 * Form builder; Create and display the IIT Global Header configuration settings form.
 */
function iit_global_header_config_form($form, &$form_state) {
  $form = array();

  // Text field for URL path to menu service
  $form['iit_global_header_primary_menu_service_url'] = array(
    '#type' => 'textfield',
    '#title' => t('IIT Global Header Primary Menu JSON Service URL'),
    '#size' => 100,
    '#description' => t('Full URL to server that provides the primary menu JSON data. This URL should be provided by the Drupal Services module and the Services Menu module.'),
    '#required' => TRUE,
    '#default_value' => IIT_GH_PRIMARY_MENU_SERVICE_URL,
  );

  $form['iit_global_header_secondary_menu_service_url'] = array(
    '#type' => 'textfield',
    '#title' => t('IIT Global Header Secondary Menu JSON Service URL'),
    '#size' => 100,
    '#description' => t('Full URL to server that provides the secondary menu JSON data. This URL should be provided by the Drupal Services module and the Services Menu module.'),
    '#required' => TRUE,
    '#default_value' => IIT_GH_SECONDARY_MENU_SERVICE_URL,
  );

  return system_settings_form($form);
}


/* ***************************************** */
/* API FUNCTIONS                             */
/* ***************************************** */

/**
 * Primary IIT Global Header Build Content Function
 *
 * Returns the HTML block content for the IIT Global Header block.
 * Uses the JSON menu services specified in module configuration or defaults.
 *
 * @return
 *   A String of HTML formatted content for the block content variable.
 */
function iit_global_header_build_contents() {
  $html_output = '';

  //Get JSON data from service for menus and decode to variables
  $primary_menu_contents = json_decode(utf8_encode(file_get_contents(variable_get('iit_global_header_primary_menu_service_url', IIT_GH_PRIMARY_MENU_SERVICE_URL))), TRUE);
  $secondary_menu_contents = json_decode(utf8_encode(file_get_contents(variable_get('iit_global_header_secondary_menu_service_url', IIT_GH_SECONDARY_MENU_SERVICE_URL))), TRUE);
  $primary_menu_items = $primary_menu_contents['tree'];
  $secondary_menu_items = $secondary_menu_contents['tree'];

  // Start main wrapper
  $html_output .= '<div id="iit-gh-wrapper">';

  // Build header element content
  $html_output .= '<div id="iit-gh-header-wrapper">';
  $html_output .= '<div id="iit-gh-header-container" class="container clearfix">';
  $html_output .= iit_global_header_build_header($primary_menu_items, $secondary_menu_items);
  $html_output .= '</div><!-- end #iit-gh-header-container -->';
  $html_output .= '</div><!-- end #iit-gh-header-wrapper -->';

  // Build menu area content
  $html_output .= '<div id="iit-gh-menu-wrapper">';
  $html_output .= '<div id="iit-gh-menu-container" class="container clearfix">';
  $html_output .= iit_global_header_build_menu($primary_menu_items);
  $html_output .= '</div><!-- end #iit-gh-menu-container -->';
  $html_output .= '</div><!-- end #iit-gh-menu-wrapper -->';

  // Close main wrapper
  $html_output .= '</div><!-- end #iit-gh-wrapper -->';

  return $html_output;
}

/**
 * IIT Global Header Build Header Content Function
 *
 * Returns the HTML content for the IIT Global Header header section.
 * For use inside the iit_global_header_build_contents function.
 *
 * @param primary_menu_items
 *  Associative array of primary menu items.
 *
 * @param secondary_menu_items
 *  Associative array of secondary menu items.
 *
 * @return
 *   A String of HTML formatted content for the header element.
 */
function iit_global_header_build_header($primary_menu_items, $secondary_menu_items) {
  $html_output = '';

  // Start header element wrapper
  $html_output .= '<header id="iit-gh-header">';

  // Build content
  $html_output .= '<h1>Header not implemented yet! REVISED</h1>';
  $html_output .= '<a href="http://www.iit.edu/">Illinois Institute of Technology</a>';

  // End header element wrapper
  $html_output .= '</header><!-- end #iit-gh-header -->';

  return $html_output;
}

/**
 * IIT Global Header Build Menu Content Function
 *
 * Returns the HTML content for the IIT Global Header menu section.
 * For use inside the iit_global_header_build_contents function.
 *
 * @param primary_menu_items
 *  Associative array of primary menu items.
 *
 * @return
 *   A String of HTML formatted content for the menu element.
 */
function iit_global_header_build_menu($primary_menu_items) {
  $html_output = '';

  return $html_output;
}












